// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "https://kao6btca3veophxpbhu4ro7qym.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z3mjm7vubnhezmb7kknpmqziwq",
    "img_url": "https://assets-shopbmwusa.realityi.com/assets/images/highquality/"
};

export default awsmobile;